version: '3.8'
services:
  github-mcp-server:
    image: ghcr.io/github/github-mcp-server
    stdin_open: true
    tty: true
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      # Optional configurations:
      # - GITHUB_READ_ONLY=1
      # - GITHUB_DYNAMIC_TOOLSETS=1