name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
        
    - name: Install extension dependencies
      run: |
        cd chrome-extension
        npm ci
        
    - name: Build extension
      run: |
        cd chrome-extension
        npm run build
        
    - name: Run E2E tests
      env:
        # Required environment variables for E2E tests
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
        # Optional environment variables (will use dummy values if not set)
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        
        # CI environment detection
        CI: true
        GITHUB_ACTIONS: true
      run: |
        cd chrome-extension
        npm run test:e2e
        
    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-screenshots
        path: chrome-extension/tests/e2e/screenshots/
        retention-days: 7
